### PR TITLE
Feature/update cart

### PR DESCRIPTION
**Pull request by kevinburnside**
-Created code to change quantities
-storage is not working though
-getting a "500" error when I try to pass the quantity to the backend

### CODE REVIEW

**Comment by aagavin** [comment]
tasked to @MavOmidK 

then tasked to @aagavin

**Comment by aagavin** [comment]
Hey why do the item swap around?

**Comment by aagavin** [comment]
@MavOmidK fixed cart

**Review by MavOmidK — APPROVED** [review]
works

**Pull request merged**
